---

services:
  wagtail:
    build:
      context: .
    command: make run-server
    volumes:
      - ./app:/app:delegated
    environment:
      DATABASE_URL: postgres://wagtail:development@postgres:5432/alloydflanagan
    ports:
      - "8080:8080"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: wagtail
      POSTGRES_PASSWORD: development
      POSTGRES_DB: alloydflanagan
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth-host=md5
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: 'redis:7'
    restart: on-failure
    volumes:
      - redis:/data

volumes:
  dbdata: {}
  redis: {}
