---

services:
  wagtail:
    build:
      context: .
    command: make run-server
    volumes:
      # don't link .venv! TODO: find simpler dir organization
      - ./app/.yarn:/app/.yarn:delegated
      - ./app/.yarnrc.yml:/app/.yarnrc:delegated
      - ./app/alloydflanagan:/app/alloydflanagan:delegated
      - ./app/Makefile:/app/Makefile:delegated
      - ./app/manage.py:/app/manage.py:delegated
      - ./app/media:/app/media:delegated
      - ./app/package.json:/app/package.json:delegated
      - ./app/pyproject.toml:/app/pyproject.toml:delegated
      - ./app/uv.lock:/app/uv.lock:delegated
      - ./app/yarn.lock:/app/yarn.lock:delegated
    environment:
      DATABASE_URL: postgres://wagtail:development@postgres:5432/alloydflanagan
    ports:
      - "8080:8080"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: wagtail
      POSTGRES_PASSWORD: development
      POSTGRES_DB: alloydflanagan
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth-host=md5
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: 'redis:7'
    restart: on-failure
    volumes:
      - redis:/data

volumes:
  dbdata: {}
  redis: {}
