---

services:
  wagtail:
    image: alflanagan-wagtail-dev
    build:
      context: .
    container_name: alf-wag
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app:delegated
    environment:
      DATABASE_URL: postgres://wagtail:development@postgres:5432/alloydflanagan
    ports:
      - "8000:8000"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: development
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth-host=md5
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: 'redis:7'
    container_name: "goz-redis"
    restart: on-failure
    volumes:
      - redis:/data

volumes:
  dbdata: {}
  redis: {}
