[tool.isort]
line_length = 120
known_django = "django"
known_wagtail = "wagtail"
sections = ["FUTURE","STDLIB","DJANGO","WAGTAIL","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = "migrations"

[tool.black]
line-length = 120
exclude = '''
  migrations
'''
