# Generated by Django 5.2.7 on 2025-11-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateField(blank=True, help_text='"Official" date post was written', null=True, verbose_name='Post Date')),
                ('primary_image', models.ImageField(null=True, upload_to='blog/images/')),
                ('content', models.TextField()),
                ('intro', models.CharField(default='', max_length=250)),
                ('body', models.TextField()),
            ],
        ),
    ]
