# Generated by Django 4.2.21 on 2025-06-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogindexpage_intro_blogpost_body_blogpost_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='intro',
            field=models.CharField(default='', max_length=250),
        ),
    ]
