# Generated by Django 4.2.21 on 2025-06-21 18:14

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, default=''),
        ),
    ]
