# Generated by Django 4.2.21 on 2025-06-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='resume',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
