# Generated by Django 4.2.21 on 2025-06-29 16:17

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.blocks.StreamBlock([('tabs', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('target', wagtail.blocks.PageChooserBlock(required=False))]))), ('banner', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, use_json_field=True),
        ),
    ]
