# Generated by Django 4.2.21 on 2025-07-12 19:05

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_multi_targets_for_menu_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="header",
            field=wagtail.fields.StreamField(
                [
                    (
                        "header",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "tabs",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "targetPage",
                                                    wagtail.blocks.PageChooserBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "targetDoc",
                                                    wagtail.documents.blocks.DocumentChooserBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "targetUrl",
                                                    wagtail.blocks.URLBlock(
                                                        required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                                (
                                    "banner",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
