# Generated by Django 4.2.21 on 2025-07-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_homepage_header"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="resume",
        ),
    ]
