# Generated by Django 5.2.7 on 2025-11-08 21:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_homepage_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='header',
            field=wagtail.fields.StreamField([('header', 1)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.StructBlock', [[('banner', 0)]], {})}),
        ),
    ]
